language: node_js
node_js:
  - '0.10'
  - '0.8'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-fng' ]; then cd .. && eval "mv $currentfolder generator-fng" && cd generator-fng; fi

